let mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
mix.js('resources/assets/js/voss.js', 'public/js')
    .js('resources/assets/js/voss_ajax.js', 'public/js')
    .js('resources/assets/js/vender.js', 'public/js')
    .js('resources/views/cruise_plan/cruise_plan_search.js', 'public/js/cruise_plan')
    .js('resources/views/reservation/cabin/reservation_cabin_passenger_entry.js', 'public/js/reservation/cabin')
    .js('resources/views/reservation/input/reservation_input_passenger.js', 'public/js/reservation/input')
    .js('resources/views/reservation/input/reservation_input_cabin_request.js', 'public/js/reservation/input')
    .js('resources/views/reservation/input/reservation_input_question.js', 'public/js/reservation/input')
    .js('resources/views/reservation/input/reservation_input_passenger_request.js', 'public/js/reservation/input')
    .js('resources/views/reservation/reservation_rooming.js', 'public/js/reservation')
    .js('resources/views/reservation/input/reservation_input_discount.js', 'public/js/reservation/input')
    .js('resources/views/reservation/reservation_cancel.js', 'public/js/reservation')
    .js('resources/views/address/address_town_select.js', 'public/js/address')
    .js('resources/views/reservation/cabin/reservation_cabin_passenger_select.js', 'public/js/reservation/cabin')
    .js('resources/views/reservation/cabin/reservation_cabin_change_confirm.js', 'public/js/reservation/cabin')
    .js('resources/views/reservation/contact/reservation_contact_list.js', 'public/js/reservation/contact')
    .js('resources/views/reservation/printing/reservation_printing_list.js', 'public/js/reservation/printing')
    .js('resources/views/reservation/import/reservation_import_format_list.js', 'public/js/reservation/import')
    .js('resources/views/reservation/import/reservation_import_file_select.js', 'public/js/reservation/import')
    .js('resources/views/reservation/import/reservation_import_format_setting.js', 'public/js/reservation/import')
    .js('resources/views/agent/agent_list.js', 'public/js/agent')
    .js('resources/views/agent/import/agent_import_add.js', 'public/js/agent/import')
    .js('resources/views/agent/import/agent_import_confirm.js', 'public/js/agent/import')
    .js('resources/views/agent/user/agent_user_edit.js', 'public/js/agent/user')
    .js('resources/views/agent/agent_edit.js', 'public/js/agent')
    .js('resources/views/agent/agent_detail.js', 'public/js/agent')
    .js('resources/views/reservation/reception/reservation_reception_list.js', 'public/js/reservation/reception')
    .js('resources/views/user/user_password_reset.js', 'public/js/user')
    .js('resources/views/login/agent_login.js', 'public/js/login')
    .js('resources/views/reservation/reservation_detail.js', 'public/js/reservation')
    .js('resources/views/reservation/contact/reservation_contact_detail_for_aps.js', 'public/js/reservation/contact');
// .js('resources/views/end_user/venus_club/discount_ticket.js', 'public/js')
// .js('resources/views/end_user/question_sheet/upload.js', 'public/js')
// .js('resources/views/end_user/boatmenber/add.js', 'public/js')
// .js('resources/views/end_user/boatmenber/boatmenber_list.js', 'public/js')
// .js('resources/views/end_user/venus_club/history.js', 'public/js')
// .js('resources/views/end_user/mail/register_mail.js', 'public/js')
// .js('resources/views/end_user/mail/register_mail_input.js', 'public/js');


mix.sass('resources/assets/scss/voss.scss', 'public/css')
    .sass('resources/assets/scss/vender.scss', 'public/css')
    .sass('resources/views/login/agent_login.scss', 'public/css/login')
    .sass('resources/views/mypage/agent_mypage.scss', 'public/css/mypage')
    .sass('resources/views/cruise_plan/cruise_plan_search.scss', 'public/css/cruise_plan')
    .sass('resources/views/reservation/cabin/reservation_cabin_type_select.scss', 'public/css/reservation/cabin')
    .sass('resources/views/reservation/cabin/reservation_cabin_passenger_select.scss', 'public/css/reservation/cabin')
    .sass('resources/views/reservation/input/reservation_input_passenger.scss', 'public/css/reservation/input')
    .sass('resources/views/reservation/input/reservation_input_cabin_request.scss', 'public/css/reservation/input')
    .sass('resources/views/reservation/cabin/reservation_cabin_passenger_entry.scss', 'public/css/reservation/cabin')
    .sass('resources/views/reservation/input/reservation_input_discount.scss', 'public/css/reservation/input')
    .sass('resources/views/reservation/input/reservation_input_question.scss', 'public/css/reservation/input')
    .sass('resources/views/reservation/input/reservation_input_passenger_request.scss', 'public/css/reservation/input')
    .sass('resources/views/reservation/cabin/reservation_cabin_change_confirm.scss', 'public/css/reservation/cabin')
    .sass('resources/views/reservation/reservation_rooming.scss', 'public/css/reservation')
    .sass('resources/views/reservation/reservation_detail.scss', 'public/css/reservation')
    .sass('resources/views/reservation/reservation_cancel.scss', 'public/css/reservation')
    .sass('resources/views/address/address_prefecture_select.scss', 'public/css/address')
    .sass('resources/views/address/address_city_select.scss', 'public/css/address')
    .sass('resources/views/address/address_town_select.scss', 'public/css/address')
    .sass('resources/views/reservation/reservation_telephone.scss', 'public/css/reservation')
    .sass('resources/views/reservation/document/reservation_document_list.scss', 'public/css/reservation/document')
    .sass('resources/views/reservation/printing/reservation_printing_list.scss', 'public/css/reservation/printing')
    .sass('resources/views/reservation/contact/reservation_contact_list.scss', 'public/css/reservation/contact')
    .sass('resources/views/reservation/contact/reservation_contact_detail.scss', 'public/css/reservation/contact')
    .sass('resources/views/reservation/import/reservation_import_result.scss', 'public/css/reservation/import')
    .sass('resources/views/reservation/import/reservation_import_format_list.scss', 'public/css/reservation/import')
    .sass('resources/views/reservation/import/reservation_import_format_setting.scss', 'public/css/reservation/import')
    .sass('resources/views/reservation/import/reservation_import_file_select.scss', 'public/css/reservation/import')
    .sass('resources/views/agent/agent_list.scss', 'public/css/agent')
    .sass('resources/views/agent/agent_edit.scss', 'public/css/agent')
    .sass('resources/views/agent/import/agent_import_add.scss', 'public/css/agent/import')
    .sass('resources/views/agent/import/agent_import_confirm.scss', 'public/css/agent/import')
    .sass('resources/views/agent/import/agent_import_complete.scss', 'public/css/agent/import')
    .sass('resources/views/agent/agent_detail.scss', 'public/css/agent')
    .sass('resources/views/agent/user/agent_user_edit.scss', 'public/css/agent/user')
    .sass('resources/views/reservation/reception/reservation_reception_list.scss', 'public/css/reservation/reception')
    .sass('resources/views/error/error.scss', 'public/css/error')
    .sass('resources/views/user/user_password_reset.scss', 'public/css/user')
    .sass('resources/views/reservation/contact/reservation_contact_detail_for_aps.scss', 'public/css/reservation/contact');
// .sass('resources/views/end_user/login/user_login.scss', 'public/css')
// .sass('resources/views/end_user/mail/forget_password.scss', 'public/css')
// .sass('resources/views/end_user/mail/register_mail.scss', 'public/css')
// .sass('resources/views/end_user/mail/register_mail_input.scss', 'public/css')
// .sass('resources/views/end_user/user_mypage.scss', 'public/css')
// .sass('resources/views/end_user/user_data/user_edit.scss', 'public/css')
// .sass('resources/views/end_user/user_data/user_add.scss', 'public/css')
// .sass('resources/views/end_user/user_data/id_edit.scss', 'public/css')
// .sass('resources/views/end_user/user_data/password_edit.scss', 'public/css')
// .sass('resources/views/end_user/user_data/user_delete.scss', 'public/css')
// .sass('resources/views/end_user/boatmenber/boatmenber_list.scss', 'public/css')
// .sass('resources/views/end_user/boatmenber/boatmenber_add.scss', 'public/css')
// .sass('resources/views/end_user/boatmenber/boatmenber_confirm.scss', 'public/css')
// .sass('resources/views/end_user/question_sheet/health.scss', 'public/css')
// .sass('resources/views/end_user/question_sheet/food.scss', 'public/css')
// .sass('resources/views/end_user/question_sheet/assist.scss', 'public/css')
// .sass('resources/views/end_user/question_sheet/upload.scss', 'public/css')
// .sass('resources/views/end_user/pay_off/agreement.scss', 'public/css')
// .sass('resources/views/end_user/pay_off/pay_select.scss', 'public/css')
// .sass('resources/views/end_user/venus_club/venus_login.scss', 'public/css')
// .sass('resources/views/end_user/venus_club/menu.scss', 'public/css')
// .sass('resources/views/end_user/venus_club/confirm.scss', 'public/css')
// .sass('resources/views/end_user/venus_club/edit.scss', 'public/css')
// .sass('resources/views/end_user/venus_club/history.scss', 'public/css')
// .sass('resources/views/end_user/venus_club/discount_ticket.scss', 'public/css');

if (mix.inProduction()) {
    mix.version();
}